/**
 * GitPopular
 */
import {
  ACTION_MARKS_LOAD_SUCCESS
} from '../../screens/githubpopular/mycenter/marks/marks-actions-types';
import {
  ACTION_LANGUAGES_LOAD_SUCCESS
} from '../../screens/githubpopular/mycenter/langus/langus-actions-types';
import {
  ACTION_THEME_INIT,
  ACTION_THEME_CHANGE,
  ACTION_THEME_SHOW_CHOICE_VIEW
} from '../../screens/githubpopular/mycenter/theme/theme-actions-types';
import {
  ACTION_POPULAR_REFRESH,
  ACTION_POPULAR_REFRESH_FAIL,
  ACTION_POPULAR_REFRESH_SUCCESS,
  ACTION_POPULAR_LOAD_MORE,
  ACTION_POPULAR_LOAD_MORE_FAIL,
  ACTION_POPULAR_LOAD_MORE_SUCCESS,
  ACTION_POPULAR_FLUSH_FAVOURITE,
  ACTION_POPULAR_NO_MORE_DATA,
  ACTION_POPULAR_EMPTY_DATA
} from '../../screens/githubpopular/popular/popular-actions-types';
import {
  ACTION_TRENDING_REFRESH,
  ACTION_TRENDING_REFRESH_FAIL,
  ACTION_TRENDING_REFRESH_SUCCESS,
  ACTION_TRENDING_LOAD_MORE,
  ACTION_TRENDING_LOAD_MORE_FAIL,
  ACTION_TRENDING_LOAD_MORE_SUCCESS,
  ACTION_TRENDING_FLUSH_FAVOURITE,
  ACTION_TRENDING_NO_MORE_DATA,
  ACTION_TRENDING_EMPTY_DATA
} from '../../screens/githubpopular/trending/trending-actions-types';
import {
  ACTION_FAVOURITE_REFRESH,
  ACTION_FAVOURITE_REFRESH_FAIL,
  ACTION_FAVOURITE_REFRESH_SUCCESS,
  ACTION_FAVOURITE_LOAD_MORE,
  ACTION_FAVOURITE_LOAD_MORE_FAIL,
  ACTION_FAVOURITE_LOAD_MORE_SUCCESS,
  ACTION_FAVOURITE_FLUSH_FAVOURITE,
  ACTION_FAVOURITE_NO_MORE_DATA,
  ACTION_FAVOURITE_EMPTY_DATA
} from '../../screens/githubpopular/favourite/favourite-actions-types';


/**
 * MeiTuanFood
 */
import {
  ACTION_MEITUAN_HOME_REFRESH,
  ACTION_MEITUAN_HOME_REFRESH_FAIL,
  ACTION_MEITUAN_HOME_REFRESH_SUCCESS,
  ACTION_MEITUAN_HOME_LOAD_MORE,
  ACTION_MEITUAN_HOME_LOAD_MORE_FAIL,
  ACTION_MEITUAN_HOME_LOAD_MORE_SUCCESS,
  ACTION_MEITUAN_HOME_NO_MORE_DATA,
  ACTION_MEITUAN_HOME_EMPTY_DATA
} from '../../screens/meituanfood/tab-home/home-actions-types';
import {
  ACTION_MEITUAN_NEARBY_TAB_REFRESH,
  ACTION_MEITUAN_NEARBY_TAB_REFRESH_FAIL,
  ACTION_MEITUAN_NEARBY_TAB_REFRESH_SUCCESS,
  ACTION_MEITUAN_NEARBY_TAB_LOAD_MORE,
  ACTION_MEITUAN_NEARBY_TAB_LOAD_MORE_FAIL,
  ACTION_MEITUAN_NEARBY_TAB_LOAD_MORE_SUCCESS,
  ACTION_MEITUAN_NEARBY_TAB_NO_MORE_DATA,
  ACTION_MEITUAN_NEARBY_TAB_EMPTY_DATA
} from '../../screens/meituanfood/tab-nearby/nearby-tab-actions-types';
import {
  ACTION_MEITUAN_GOODS_DETAIL_REFRESH,
  ACTION_MEITUAN_GOODS_DETAIL_REFRESH_FAIL,
  ACTION_MEITUAN_GOODS_DETAIL_REFRESH_SUCCESS,
  ACTION_MEITUAN_GOODS_DETAIL_LOAD_MORE,
  ACTION_MEITUAN_GOODS_DETAIL_LOAD_MORE_FAIL,
  ACTION_MEITUAN_GOODS_DETAIL_LOAD_MORE_SUCCESS,
  ACTION_MEITUAN_GOODS_DETAIL_NO_MORE_DATA,
  ACTION_MEITUAN_GOODS_DETAIL_EMPTY_DATA
} from '../../screens/meituanfood/goods-detail/goods-detail-actions-types';


/**
 * 导出
 */
export default {
  // 主题
  ACTION_THEME_INIT,
  ACTION_THEME_CHANGE,
  ACTION_THEME_SHOW_CHOICE_VIEW,

  // 标签
  ACTION_MARKS_LOAD_SUCCESS,
  // 语言
  ACTION_LANGUAGES_LOAD_SUCCESS,

  // 最热
  ACTION_POPULAR_REFRESH,
  ACTION_POPULAR_REFRESH_FAIL,
  ACTION_POPULAR_REFRESH_SUCCESS,
  ACTION_POPULAR_LOAD_MORE,
  ACTION_POPULAR_LOAD_MORE_FAIL,
  ACTION_POPULAR_LOAD_MORE_SUCCESS,
  ACTION_POPULAR_FLUSH_FAVOURITE,
  ACTION_POPULAR_NO_MORE_DATA,
  ACTION_POPULAR_EMPTY_DATA,

  // 趋势
  ACTION_TRENDING_REFRESH,
  ACTION_TRENDING_REFRESH_FAIL,
  ACTION_TRENDING_REFRESH_SUCCESS,
  ACTION_TRENDING_LOAD_MORE,
  ACTION_TRENDING_LOAD_MORE_FAIL,
  ACTION_TRENDING_LOAD_MORE_SUCCESS,
  ACTION_TRENDING_FLUSH_FAVOURITE,
  ACTION_TRENDING_NO_MORE_DATA,
  ACTION_TRENDING_EMPTY_DATA,

  // 收藏
  ACTION_FAVOURITE_REFRESH,
  ACTION_FAVOURITE_REFRESH_FAIL,
  ACTION_FAVOURITE_REFRESH_SUCCESS,
  ACTION_FAVOURITE_LOAD_MORE,
  ACTION_FAVOURITE_LOAD_MORE_FAIL,
  ACTION_FAVOURITE_LOAD_MORE_SUCCESS,
  ACTION_FAVOURITE_FLUSH_FAVOURITE,
  ACTION_FAVOURITE_NO_MORE_DATA,
  ACTION_FAVOURITE_EMPTY_DATA,

  // 美团 - 主页
  ACTION_MEITUAN_HOME_REFRESH,
  ACTION_MEITUAN_HOME_REFRESH_FAIL,
  ACTION_MEITUAN_HOME_REFRESH_SUCCESS,
  ACTION_MEITUAN_HOME_LOAD_MORE,
  ACTION_MEITUAN_HOME_LOAD_MORE_FAIL,
  ACTION_MEITUAN_HOME_LOAD_MORE_SUCCESS,
  ACTION_MEITUAN_HOME_NO_MORE_DATA,
  ACTION_MEITUAN_HOME_EMPTY_DATA,

  // 美团 - 附近
  ACTION_MEITUAN_NEARBY_TAB_REFRESH,
  ACTION_MEITUAN_NEARBY_TAB_REFRESH_FAIL,
  ACTION_MEITUAN_NEARBY_TAB_REFRESH_SUCCESS,
  ACTION_MEITUAN_NEARBY_TAB_LOAD_MORE,
  ACTION_MEITUAN_NEARBY_TAB_LOAD_MORE_FAIL,
  ACTION_MEITUAN_NEARBY_TAB_LOAD_MORE_SUCCESS,
  ACTION_MEITUAN_NEARBY_TAB_NO_MORE_DATA,
  ACTION_MEITUAN_NEARBY_TAB_EMPTY_DATA,

  // 美团 - 商品
  ACTION_MEITUAN_GOODS_DETAIL_REFRESH,
  ACTION_MEITUAN_GOODS_DETAIL_REFRESH_FAIL,
  ACTION_MEITUAN_GOODS_DETAIL_REFRESH_SUCCESS,
  ACTION_MEITUAN_GOODS_DETAIL_LOAD_MORE,
  ACTION_MEITUAN_GOODS_DETAIL_LOAD_MORE_FAIL,
  ACTION_MEITUAN_GOODS_DETAIL_LOAD_MORE_SUCCESS,
  ACTION_MEITUAN_GOODS_DETAIL_NO_MORE_DATA,
  ACTION_MEITUAN_GOODS_DETAIL_EMPTY_DATA,
};
