import { ACTION_MARKS_LOAD_SUCCESS } from '../../screens/mycenter/marks/marks-actions-types';
import { ACTION_LANGUAGES_LOAD_SUCCESS } from '../../screens/mycenter/langus/langus-actions-types';
import {
  ACTION_THEME_INIT,
  ACTION_THEME_CHANGE,
  ACTION_THEME_SHOW_CHOICE_VIEW
} from '../../screens/mycenter/theme/theme-actions-types';
import {
  ACTION_POPULAR_REFRESH,
  ACTION_POPULAR_REFRESH_FAIL,
  ACTION_POPULAR_REFRESH_SUCCESS,
  ACTION_POPULAR_LOAD_MORE,
  ACTION_POPULAR_LOAD_MORE_FAIL,
  ACTION_POPULAR_LOAD_MORE_SUCCESS,
  ACTION_POPULAR_FLUSH_FAVOURITE,
  ACTION_POPULAR_NO_MORE_DATA,
  ACTION_POPULAR_EMPTY_DATA
} from '../../screens/popular/popular-actions-types';
import {
  ACTION_TRENDING_REFRESH,
  ACTION_TRENDING_REFRESH_FAIL,
  ACTION_TRENDING_REFRESH_SUCCESS,
  ACTION_TRENDING_LOAD_MORE,
  ACTION_TRENDING_LOAD_MORE_FAIL,
  ACTION_TRENDING_LOAD_MORE_SUCCESS,
  ACTION_TRENDING_FLUSH_FAVOURITE,
  ACTION_TRENDING_NO_MORE_DATA,
  ACTION_TRENDING_EMPTY_DATA
} from '../../screens/trending/trending-actions-types';


export default {
  // 主题
  ACTION_THEME_INIT,
  ACTION_THEME_CHANGE,
  ACTION_THEME_SHOW_CHOICE_VIEW,

  // 标签
  ACTION_MARKS_LOAD_SUCCESS,
  // 语言
  ACTION_LANGUAGES_LOAD_SUCCESS,

  // 最热
  ACTION_POPULAR_REFRESH,
  ACTION_POPULAR_REFRESH_FAIL,
  ACTION_POPULAR_REFRESH_SUCCESS,
  ACTION_POPULAR_LOAD_MORE,
  ACTION_POPULAR_LOAD_MORE_FAIL,
  ACTION_POPULAR_LOAD_MORE_SUCCESS,
  ACTION_POPULAR_FLUSH_FAVOURITE,
  ACTION_POPULAR_NO_MORE_DATA,
  ACTION_POPULAR_EMPTY_DATA,

  // 趋势
  ACTION_TRENDING_REFRESH,
  ACTION_TRENDING_REFRESH_FAIL,
  ACTION_TRENDING_REFRESH_SUCCESS,
  ACTION_TRENDING_LOAD_MORE,
  ACTION_TRENDING_LOAD_MORE_FAIL,
  ACTION_TRENDING_LOAD_MORE_SUCCESS,
  ACTION_TRENDING_FLUSH_FAVOURITE,
  ACTION_TRENDING_NO_MORE_DATA,
  ACTION_TRENDING_EMPTY_DATA,
};
