/**
 * React Native
 * https://github.com/facebook/react-native
 */

export const EVENT_BOTTOM_TAB_CHANGE_SELECT = 'EVENT_BOTTOM_TAB_CHANGE_SELECT';
export const EVENT_FAVOURITE_CHANGED_POPULAR = 'EVENT_FAVOURITE_CHANGED_POPULAR';
export const EVENT_FAVOURITE_CHANGED_TRENDING = 'EVENT_FAVOURITE_CHANGED_TRENDING';
